services:
  db:
    image: mysql:latest
    container_name: db-en
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: en_db
      MYSQL_USER: en_user
      MYSQL_PASSWORD: en_password
    volumes:
      - ./database:/var/lib/mysql  # Volumen persistente para la base de datos
    ports:
      - "3307:3306"
    networks:
      - my_custom_network

  web:
    build:
      context: .  # Dockerfile en la raíz
      dockerfile: Dockerfile
    container_name: web-en
    restart: always
    volumes:
      - .:/usr/src/app  # Monta el proyecto para ver cambios en tiempo real
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: en_db
      DB_USER: en_user
      DB_PASSWORD: en_password
    networks:
      - my_custom_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-en
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: en_user
      PMA_PASSWORD: en_password
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge