# Generated by Django 3.2.20 on 2024-11-13 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Encuesta')),
                ('is_active', models.BooleanField(default=False, verbose_name='Encuesta Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Texto de la Pregunta')),
                ('question_type', models.CharField(choices=[('text', 'Respuesta Única'), ('multiple_choice', 'Selección Múltiple')], max_length=20, verbose_name='Tipo de Pregunta')),
                ('choices', models.JSONField(blank=True, null=True, verbose_name='Opciones de Selección Múltiple')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='encuestas.survey', verbose_name='Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID de Usuario')),
                ('response', models.TextField(verbose_name='Respuesta del Usuario')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='encuestas.question', verbose_name='Pregunta')),
            ],
        ),
    ]
