# Generated by Django 3.2.20 on 2024-11-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Opciones de Selección Múltiple'),
        ),
    ]
