# Generated by Django 3.2.20 on 2024-11-13 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_alter_question_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, null=True, verbose_name='Opciones de Selección Múltiple'),
        ),
        migrations.CreateModel(
            name='SurveyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Encuesta Activa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='encuestas.survey')),
            ],
        ),
    ]
